//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiyayaTravelAssist.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuditTrail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AuditTrail()
        {
            this.Employees = new HashSet<Employee>();
        }
    
        public int AuditTrailID { get; set; }
        public Nullable<System.DateTime> AuditTrailDate { get; set; }
        public Nullable<System.DateTime> AuditTrailTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
