//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiyayaTravelAssist.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        public int BookingID { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string BookingStatus { get; set; }
        public string BookingReference { get; set; }
        public string BookingOrder { get; set; }
        public Nullable<int> numberOfPassengers { get; set; }
        public string PaymentStatus { get; set; }
        public string AdditionalInformation { get; set; }
        public Nullable<int> QuoteID { get; set; }
        public Nullable<int> BookingTypeID { get; set; }
    
        public virtual BookingType BookingType { get; set; }
        public virtual Quote Quote { get; set; }
    }
}
