//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiyayaTravelAssist.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Driver
    {
        public int DriverID { get; set; }
        public string LicenseNumber { get; set; }
        public Nullable<System.DateTime> LicenseExpiryDate { get; set; }
        public string OutsourceName { get; set; }
        public string OutsourceNumber { get; set; }
        public string OutsourseIdentityNumber { get; set; }
        public Nullable<int> LicenseTypeID { get; set; }
        public Nullable<int> DriverTypeID { get; set; }
        public Nullable<int> EmployeeID { get; set; }
    
        public virtual DriverType DriverType { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual LicenseType LicenseType { get; set; }
    }
}
