//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiyayaTravelAssist.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Drivers = new HashSet<Driver>();
        }
    
        public int EmployeeID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailAddress { get; set; }
        public string Telephone { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Password { get; set; }
        public Nullable<bool> IsEmailVerified { get; set; }
        public Nullable<int> EmployeeTypeID { get; set; }
        public Nullable<int> CountryID { get; set; }
        public Nullable<int> TitleID { get; set; }
        public Nullable<int> ProvinceID { get; set; }
        public Nullable<int> SuburbID { get; set; }
        public Nullable<int> AuditTrailID { get; set; }
        public Nullable<int> AccessLevelID { get; set; }
        public Nullable<int> NationalityID { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> Gender { get; set; }
    
        public virtual AccessLevel AccessLevel { get; set; }
        public virtual AuditTrail AuditTrail { get; set; }
        public virtual Country Country { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Driver> Drivers { get; set; }
        public virtual EmployeeType EmployeeType { get; set; }
        public virtual Nationality Nationality { get; set; }
        public virtual Province Province { get; set; }
        public virtual Suburb Suburb { get; set; }
        public virtual Title Title { get; set; }
        public virtual City City { get; set; }
        public virtual Gender Gender1 { get; set; }
    }
}
