//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiyayaTravelAssist.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trip
    {
        public int TripID { get; set; }
        public Nullable<System.DateTime> PickupTime { get; set; }
        public Nullable<System.DateTime> DropOffTime { get; set; }
        public Nullable<System.DateTime> TripDate { get; set; }
        public Nullable<int> PassengerID { get; set; }
        public Nullable<int> PickupLocation { get; set; }
        public Nullable<int> DropOffLocation { get; set; }
        public string Distance { get; set; }
        public Nullable<int> QuoteID { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual Location Location1 { get; set; }
        public virtual Passenger Passenger { get; set; }
        public virtual Quote Quote { get; set; }
    }
}
