//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiyayaTravelAssist.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicle()
        {
            this.VehicleMaintenances = new HashSet<VehicleMaintenance>();
        }
    
        public int VehicleID { get; set; }
        public string VehicleLicenseNumber { get; set; }
        public Nullable<int> VehicleBrandTypeID { get; set; }
        public Nullable<int> VehicleColorID { get; set; }
        public Nullable<int> VehicleGroupID { get; set; }
        public Nullable<int> VehicleTypeID { get; set; }
        public Nullable<int> OutsourceVehicleGroupCompaniesID { get; set; }
    
        public virtual OutsourceVehicleGroupCompany OutsourceVehicleGroupCompany { get; set; }
        public virtual VehicleBrandType VehicleBrandType { get; set; }
        public virtual VehicleColor VehicleColor { get; set; }
        public virtual VehicleGroup VehicleGroup { get; set; }
        public virtual VehicleType VehicleType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VehicleMaintenance> VehicleMaintenances { get; set; }
    }
}
