//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SiyayaTravelAssist.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VehicleMaintenance
    {
        public int VehicleMaintenanceID { get; set; }
        public string KmToMaintenance { get; set; }
        public Nullable<bool> MaintenanceStatus { get; set; }
        public Nullable<System.DateTime> MaintenanceDate { get; set; }
        public Nullable<int> VehicleID { get; set; }
        public Nullable<int> ServiceProviderID { get; set; }
    
        public virtual ServiceProvider ServiceProvider { get; set; }
        public virtual Vehicle Vehicle { get; set; }
    }
}
